import {
  Pesebrera,
  Horse,
  Client,
  VeterinaryRecord,
  PaymentRecord,
  DashboardMetrics,
  InventoryItem,
  FeedTemplate,
  CenterSettings,
  CanonPlan,
  UserAccount,
} from "@/types";

export const initialClients: Client[] = [
  {
    id: "cli-1",
    fullName: "Carlos Eduardo Restrepo",
    identification: "CC 71.392.810",
    email: "carlos.restrepo@haciendaecuestre.com",
    phone: "+573124589012",
    address: "Finca El Remanso, Vereda Las Palmas",
    horsesCount: 2,
    paymentStatus: "al_dia",
    outstandingBalance: 0,
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "cli-2",
    fullName: "María Camila Gómez",
    identification: "CC 1.020.485.920",
    email: "camilagomez@criaderolailusion.co",
    phone: "+573208901234",
    address: "Km 4 Vía Rionegro",
    horsesCount: 3,
    paymentStatus: "pendiente",
    outstandingBalance: 1200000,
    createdAt: "2025-01-15T12:00:00Z",
    updatedAt: "2025-02-01T15:30:00Z",
  },
  {
    id: "cli-3",
    fullName: "Andrés Felipe Mendoza",
    identification: "CC 98.765.432",
    email: "af.mendoza@agroganadera.com",
    phone: "+573016783456",
    address: "Condominio Campestre Los Álamos",
    horsesCount: 1,
    paymentStatus: "al_dia",
    outstandingBalance: 0,
    createdAt: "2025-02-01T08:00:00Z",
    updatedAt: "2025-02-01T08:00:00Z",
  },
  {
    id: "cli-4",
    fullName: "Valentina Osorio Ríos",
    identification: "CC 1.036.789.012",
    email: "valen.osorio@equinoscolombia.com",
    phone: "+573105557890",
    address: "Sector La Fe, El Retiro",
    horsesCount: 1,
    paymentStatus: "al_dia",
    outstandingBalance: 0,
    createdAt: "2025-02-10T09:00:00Z",
    updatedAt: "2025-02-10T09:00:00Z",
  },
];

const _nowMs = Date.now();
const _oneDayMs = 24 * 60 * 60 * 1000;
const _fmtDate = (ms: number) => new Date(ms).toISOString().split("T")[0];

export const initialHorses: Horse[] = [
  {
    id: "horse-1",
    name: "Relámpago de San Isidro",
    breed: "Paso Fino Colombiano",
    gender: "macho",
    coatColor: "Castaño Cerrado",
    birthDate: "2020-04-12",
    ageYears: 6,
    microchip: "COL-982-000-451",
    passportNumber: "PFC-2020-994",
    ownerId: "cli-1",
    ownerName: "Carlos Eduardo Restrepo",
    pesebreraId: "box-01",
    pesebreraCode: "BOX-A01",
    healthStatus: "optimo",
    dietNotes: "3 raciones de heno pangola + suplemento de salvado y minerales AM/PM",
    imageUrl: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80",
    planCode: "TIPO_A",
    planName: "Pesebrera Tipo A (Integral)",
    planPriceCOP: 1600000,
    dailyPortionsCount: 3,
    scheduledForRidingToday: true,
    assignedRiderName: "Montador Carlos Valderrama",
    ridingActivityType: "Pista de adiestramiento & galope",
    dailyActivityHistory: [
      {
        id: "act-h1-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-1",
        horseName: "Relámpago de San Isidro",
        ownerId: "cli-1",
        ownerName: "Carlos Eduardo Restrepo",
        boxCode: "BOX-A01",
        portionsServedCount: 2,
        totalPortionsPlanned: 3,
        portionsDetails: [
          { portionNumber: 1, label: "Ración 1", served: true, servedAt: "06:30 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 2, label: "Ración 2", served: true, servedAt: "12:00 PM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 3, label: "Ración 3", served: false },
        ],
        wasRidden: true,
        ridingScheduled: true,
        ridingActivity: "Sesión de pista, arreglo de cabeza y ritmo (45 min)",
        riderName: "Montador Carlos Valderrama",
        generalCare: {
          bathed: true,
          hoovesCleaned: true,
          stableCleaned: true,
          grooming: true,
        },
        notes: "Excelente respuesta a la embocadura. Aplomos y marcha firmes.",
        completedAt: new Date(_nowMs - 2 * 3600000).toISOString(),
        reportedBy: "Mayordomo Cuadras",
        publishedToOwner: true,
      },
    ],
    ridingSessionHistory: [
      {
        id: "rs-h1-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-1",
        horseName: "Relámpago de San Isidro",
        ownerId: "cli-1",
        ownerName: "Carlos Eduardo Restrepo",
        boxCode: "BOX-A01",
        riderName: "Carlos Valderrama (Montador Titular)",
        sessionType: "Pista y arreglo",
        durationMinutes: 45,
        attitude: "excelente",
        exercisesWorked: [
          "Flexión de nuca y cuello",
          "Arreglo de cabeza y embocadura",
          "Transición suave paso a trocha",
          "Círculos y ochos reunidos",
        ],
        technicalNotes: "El ejemplar respondió con gran docilidad a la rienda suave. Muy centrado en su andadura, braceo rítmico y aplomos firmes. Trabajo de dorso y colocación impecables.",
        completedAt: new Date(_nowMs - 2 * 3600000).toISOString(),
        publishedToOwner: true,
      },
      {
        id: "rs-h1-prev",
        date: _fmtDate(_nowMs - _oneDayMs),
        horseId: "horse-1",
        horseName: "Relámpago de San Isidro",
        ownerId: "cli-1",
        ownerName: "Carlos Eduardo Restrepo",
        boxCode: "BOX-A01",
        riderName: "Carlos Valderrama (Montador Titular)",
        sessionType: "Rienda y embocadura",
        durationMinutes: 40,
        attitude: "buena",
        exercisesWorked: [
          "Apoyos y cesión a la pierna",
          "Paradas a raya controladas",
          "Calentamiento al paso suelto",
        ],
        technicalNotes: "Se trabajó la relajación en el tercio posterior y la colocación de la embocadura con filete. Sin contratiempos.",
        completedAt: new Date(_nowMs - 26 * 3600000).toISOString(),
        publishedToOwner: true,
      },
    ],
    feedConfig: {
      feedProvidedBy: "criadero",
      dailyGrainKg: 3.0,
      feedType: "simple",
      feedName: "Concentrado Institucional Criadero (Plan A)",
      bagWeightKg: 40,
      bagsCount: 1,
      totalKgSupplied: 40,
      startDate: _fmtDate(_nowMs - 5 * _oneDayMs),
      depletionDate: _fmtDate(_nowMs + 8 * _oneDayMs),
      alertDate: _fmtDate(_nowMs + 6 * _oneDayMs),
      lastRestockedDate: _fmtDate(_nowMs - 5 * _oneDayMs),
      restockHistory: [
        {
          id: "rst-h1",
          date: _fmtDate(_nowMs - 5 * _oneDayMs),
          kgAdded: 40,
          notes: "Asignado automáticamente por el criadero bajo Plan A",
          recordedBy: "Mayordomo / Bodega",
        },
      ],
    },
    pedigree: {
      sire: "Dulce Sueño de Lusitania",
      dam: "Silueta de La Alhambra",
      grandSirePaternal: "Capuchino",
      grandDamPaternal: "Dulce María de Lusitania",
      grandSireMaternal: "Patrimonio del 8",
      grandDamMaternal: "La Ilusión de la Sierra",
      breedingFarm: "Criadero San Isidro",
      registryNumber: "FED-PFC-88421",
      registrationDate: "2020-06-15",
    },
    diseaseHistory: [
      {
        id: "dis-1",
        diseaseName: "Cólico Espasmódico Leve",
        diagnosedDate: "2025-01-14",
        resolutionDate: "2025-01-15",
        severity: "leve",
        status: "resuelto",
        medicationsGiven: "Flunixin Meglumine (Banamine) 10ml IV + Sondaje nasogástrico con electrolitos",
        veterinarian: "Dr. Juan Pablo Morales (MVZ)",
        clinicalNotes: "Resuelto satisfactoriamente en 12 horas. Regresó a dieta normal tras 24h de papilla de afrecho.",
      },
    ],
    farrierControl: {
      lastShoeingDate: "2025-02-01",
      nextShoeingDate: "2025-03-08",
      shoeingType: "Herradura Lisa de Pista (Ranura Fina)",
      farrierName: "Maestro Jairo Restrepo",
      cost: 160000,
      notes: "Aplomos equilibrados, palma y ranilla en estado óptimo.",
    },
    createdAt: "2025-01-10T10:30:00Z",
    updatedAt: "2025-02-15T14:00:00Z",
  },
  {
    id: "horse-2",
    name: "Tormenta de La Alborada",
    breed: "Cuarto de Milla",
    gender: "hembra",
    coatColor: "Alazán",
    birthDate: "2019-08-25",
    ageYears: 7,
    microchip: "COL-982-000-882",
    passportNumber: "QM-2019-301",
    ownerId: "cli-2",
    ownerName: "María Camila Gómez",
    pesebreraId: "box-02",
    pesebreraCode: "BOX-A02",
    healthStatus: "en_tratamiento",
    dietNotes: "Heno alfalfa al 40% + suplemento articular con glucosamina y MSM",
    imageUrl: "https://images.unsplash.com/photo-1534258936925-c58bed479fcb?auto=format&fit=crop&w=800&q=80",
    planCode: "TIPO_B",
    planName: "Pesebrera Tipo B (Forraje & Cama)",
    planPriceCOP: 1050000,
    dailyPortionsCount: 5,
    scheduledForRidingToday: false,
    assignedRiderName: "En reposo médico (corvejón)",
    ridingActivityType: "Caminata controlada a mano 15 min",
    dailyActivityHistory: [
      {
        id: "act-h2-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-2",
        horseName: "Tormenta de La Alborada",
        ownerId: "cli-2",
        ownerName: "María Camila Gómez",
        boxCode: "BOX-A02",
        portionsServedCount: 4,
        totalPortionsPlanned: 5,
        portionsDetails: [
          { portionNumber: 1, label: "Ración 1", served: true, servedAt: "06:00 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 2, label: "Ración 2", served: true, servedAt: "10:00 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 3, label: "Ración 3", served: true, servedAt: "01:30 PM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 4, label: "Ración 4", served: true, servedAt: "05:00 PM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 5, label: "Ración 5", served: false },
        ],
        wasRidden: false,
        ridingScheduled: false,
        ridingActivity: "Caminata suave de rehabilitación a mano (15 min)",
        generalCare: {
          bathed: true,
          hoovesCleaned: true,
          stableCleaned: true,
        },
        notes: "Articulación del corvejón desinflamada y con buena movilidad sin claudicación.",
        completedAt: new Date(_nowMs - 3 * 3600000).toISOString(),
        reportedBy: "Mayordomo Cuadras",
        publishedToOwner: true,
      },
    ],
    feedConfig: {
      feedProvidedBy: "propietario",
      dailyGrainKg: 3.5,
      feedType: "mezcla",
      feedName: "Mezcla de Rendimiento (Pinta Campeón + Avena + Salvado)",
      blendIngredients: [
        { id: "ing-1", name: "Italcol Pinta Campeón (Bulto)", kg: 40 },
        { id: "ing-2", name: "Avena Rolada en Hojuelas", kg: 20 },
        { id: "ing-3", name: "Salvado de Trigo & Vitaminas", kg: 5 },
      ],
      totalKgSupplied: 65,
      startDate: _fmtDate(_nowMs - 16 * _oneDayMs),
      depletionDate: _fmtDate(_nowMs + 2 * _oneDayMs),
      alertDate: _fmtDate(_nowMs),
      lastRestockedDate: _fmtDate(_nowMs - 16 * _oneDayMs),
      restockHistory: [
        {
          id: "rst-h2-1",
          date: _fmtDate(_nowMs - 16 * _oneDayMs),
          kgAdded: 65,
          notes: "Compuesto preparado y pesado en tolva (40kg concentrado + 20kg avena + 5kg salvado)",
          recordedBy: "Mayordomo / Cuadras",
        },
      ],
    },
    pedigree: {
      sire: "Colonel Freckles Gold",
      dam: "Poco Lena Star",
      grandSirePaternal: "Jewel's Leo Bars",
      grandDamPaternal: "Christy Jay",
      grandSireMaternal: "Doc O'Lena",
      grandDamMaternal: "Poco Mona",
      breedingFarm: "Rancho La Alborada (Texas / Rionegro)",
      registryNumber: "AQHA-5819024",
      registrationDate: "2019-11-20",
    },
    diseaseHistory: [
      {
        id: "dis-2",
        diseaseName: "Sinovitis y Distensión Articular Corvejón Izquierdo",
        diagnosedDate: "2025-02-10",
        severity: "moderada",
        status: "en_tratamiento",
        medicationsGiven: "Ácido Hialurónico intraarticular + Fenilbutazona oral 1g/día x 5 días",
        veterinarian: "Dr. Juan Pablo Morales (MVZ)",
        clinicalNotes: "Disminución notable de la claudicación (Grado 1/5). Ejercicio restringido a caminata a mano 15 min.",
      },
      {
        id: "dis-3",
        diseaseName: "Gastroenteritis Transitoria por Cambio de Forraje",
        diagnosedDate: "2024-11-05",
        resolutionDate: "2024-11-09",
        severity: "leve",
        status: "resuelto",
        medicationsGiven: "Omeprazol pasta 4mg/kg + probióticos equinos",
        veterinarian: "Dra. Carolina Zuluaga (MVZ)",
        clinicalNotes: "Flora intestinal estabilizada sin complicaciones.",
      },
    ],
    farrierControl: {
      lastShoeingDate: "2025-01-18",
      nextShoeingDate: "2025-02-22", // Próxima o vencida
      shoeingType: "Herradura Ortopédica con Cuña Trasera (3°)",
      farrierName: "Maestro Jairo Restrepo",
      cost: 210000,
      notes: "Requiere recorte cuidadoso de talones en miembros posteriores.",
    },
    createdAt: "2025-01-15T12:30:00Z",
    updatedAt: "2025-02-18T11:20:00Z",
  },
  {
    id: "horse-3",
    name: "Monarca Real",
    breed: "Trocha y Galope",
    gender: "castrado",
    coatColor: "Tordillo Moscado",
    birthDate: "2021-02-10",
    ageYears: 5,
    microchip: "COL-982-001-105",
    passportNumber: "TYG-2021-112",
    ownerId: "cli-1",
    ownerName: "Carlos Eduardo Restrepo",
    pesebreraId: "box-03",
    pesebreraCode: "BOX-A03",
    healthStatus: "optimo",
    dietNotes: "Pasto de corte fresco + concentrado de alta energía post-entreno",
    imageUrl: "https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?auto=format&fit=crop&w=800&q=80",
    planCode: "TIPO_A",
    planName: "Pesebrera Tipo A (Integral)",
    planPriceCOP: 1600000,
    dailyPortionsCount: 4,
    scheduledForRidingToday: true,
    assignedRiderName: "Montador Sebastián Osorio",
    ridingActivityType: "Torno y arreglo de embocadura",
    dailyActivityHistory: [
      {
        id: "act-h3-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-3",
        horseName: "Monarca Real",
        ownerId: "cli-1",
        ownerName: "Carlos Eduardo Restrepo",
        boxCode: "BOX-A03",
        portionsServedCount: 3,
        totalPortionsPlanned: 4,
        portionsDetails: [
          { portionNumber: 1, label: "Ración 1", served: true, servedAt: "06:15 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 2, label: "Ración 2", served: true, servedAt: "10:30 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 3, label: "Ración 3", served: true, servedAt: "02:00 PM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 4, label: "Ración 4", served: false },
        ],
        wasRidden: true,
        ridingScheduled: true,
        ridingActivity: "Sesión de torno y trabajo de rienda (40 min)",
        riderName: "Montador Sebastián Osorio",
        generalCare: {
          bathed: true,
          hoovesCleaned: true,
          stableCleaned: true,
          grooming: true,
        },
        notes: "Buen ritmo en pista, trote y galope elásticos.",
        completedAt: new Date(_nowMs - 2 * 3600000).toISOString(),
        reportedBy: "Mayordomo Cuadras",
        publishedToOwner: true,
      },
    ],
    ridingSessionHistory: [
      {
        id: "rs-h3-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-3",
        horseName: "Monarca Real",
        ownerId: "cli-1",
        ownerName: "Carlos Eduardo Restrepo",
        boxCode: "BOX-A03",
        riderName: "Sebastián Osorio (Montador Asistente)",
        sessionType: "Torno / Cuerda",
        durationMinutes: 35,
        attitude: "buena",
        exercisesWorked: [
          "Torno a dos manos",
          "Impulsión y transiciones con la voz",
          "Estiramiento de dorso",
        ],
        technicalNotes: "Trabajo a la cuerda con jáquima acolchada para calentar antes de montar. Marcó muy bien la trocha sostenida y el galope reunido con buena cadencia.",
        completedAt: new Date(_nowMs - 3 * 3600000).toISOString(),
        publishedToOwner: true,
      },
    ],
    pedigree: {
      sire: "Hermano Sol de Villa Milena",
      dam: "Danza Tropical",
      grandSirePaternal: "Barú F.C.",
      grandDamPaternal: "Maracanazo",
      grandSireMaternal: "Relicario F.C.",
      grandDamMaternal: "La Consentida",
      breedingFarm: "Criadero Villa Real",
      registryNumber: "FED-TYG-90312",
      registrationDate: "2021-05-12",
    },
    diseaseHistory: [],
    farrierControl: {
      lastShoeingDate: "2025-02-08",
      nextShoeingDate: "2025-03-15",
      shoeingType: "Herradura de Trabajo Liviana con Bisel",
      farrierName: "Mayordomo y Herrador Asistente",
      cost: 140000,
      notes: "Casco fuerte y bien hidratado. Sin grietas.",
    },
    createdAt: "2025-01-20T09:00:00Z",
    updatedAt: "2025-02-10T16:00:00Z",
  },
  {
    id: "horse-4",
    name: "Sultán del Valle",
    breed: "Frisón",
    gender: "macho",
    coatColor: "Negro Azabache",
    birthDate: "2018-06-14",
    ageYears: 8,
    microchip: "COL-982-002-390",
    passportNumber: "FRS-2018-042",
    ownerId: "cli-3",
    ownerName: "Andrés Felipe Mendoza",
    pesebreraId: "box-04",
    pesebreraCode: "BOX-B01",
    healthStatus: "reposo",
    dietNotes: "Reposo por tendinitis leve mano derecha. Heno de gramínea restringido en azúcares.",
    imageUrl: "https://images.unsplash.com/photo-1598974357801-cbca100e6571?auto=format&fit=crop&w=800&q=80",
    planCode: "TIPO_C",
    planName: "Pesebrera Tipo C (Básica)",
    planPriceCOP: 750000,
    dailyPortionsCount: 2,
    scheduledForRidingToday: false,
    assignedRiderName: "Reposo por tendinitis",
    ridingActivityType: "Caminador eléctrico suave 15 min",
    dailyActivityHistory: [
      {
        id: "act-h4-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-4",
        horseName: "Sultán del Valle",
        ownerId: "cli-3",
        ownerName: "Andrés Felipe Mendoza",
        boxCode: "BOX-B01",
        portionsServedCount: 1,
        totalPortionsPlanned: 2,
        portionsDetails: [
          { portionNumber: 1, label: "Ración 1", served: true, servedAt: "07:00 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 2, label: "Ración 2", served: false },
        ],
        wasRidden: false,
        ridingScheduled: false,
        ridingActivity: "Caminata controlada a mano y reposo en box",
        generalCare: {
          bathed: false,
          hoovesCleaned: true,
          stableCleaned: true,
        },
        notes: "Vendaje de miembro anterior derecho cambiado. Sin calor excesivo.",
        completedAt: new Date(_nowMs - 4 * 3600000).toISOString(),
        reportedBy: "Mayordomo Cuadras",
        publishedToOwner: true,
      },
    ],
    feedConfig: {
      feedProvidedBy: "propietario",
      dailyGrainKg: 2.0,
      feedType: "simple",
      feedName: "Cavalor Strucomix Original (Bulto)",
      bagWeightKg: 40,
      bagsCount: 1,
      totalKgSupplied: 40,
      startDate: _fmtDate(_nowMs - 5 * _oneDayMs),
      depletionDate: _fmtDate(_nowMs + 15 * _oneDayMs),
      alertDate: _fmtDate(_nowMs + 13 * _oneDayMs),
      lastRestockedDate: _fmtDate(_nowMs - 5 * _oneDayMs),
      restockHistory: [
        {
          id: "rst-h4-1",
          date: _fmtDate(_nowMs - 5 * _oneDayMs),
          kgAdded: 40,
          notes: "Bulto sellado entregado por Don Andrés Mendoza",
          recordedBy: "Bodega Cuadras",
        },
      ],
    },
    pedigree: {
      sire: "Jasper 366 Sport",
      dam: "Froukje van der Linden",
      grandSirePaternal: "Olof 315",
      grandDamPaternal: "Antje fan de Poel",
      grandSireMaternal: "Teunis 332",
      grandDamMaternal: "Geertje Ster",
      breedingFarm: "KFPS Royal Friesian Stud (Países Bajos / Importado)",
      registryNumber: "KFPS-201802914",
      registrationDate: "2018-09-01",
    },
    diseaseHistory: [
      {
        id: "dis-4",
        diseaseName: "Desgarro Tendón Flexor Digital Superficial",
        diagnosedDate: "2025-02-12",
        severity: "moderada",
        status: "en_tratamiento",
        medicationsGiven: "Vendajes fríos de arcilla + Terapia regenerativa con PRP (Plasma Rico en Plaquetas)",
        veterinarian: "Dra. Carolina Zuluaga (MVZ)",
        clinicalNotes: "En reposo absoluto en box B-01. Piso de caucho vulcanizado reduce el impacto.",
      },
    ],
    farrierControl: {
      lastShoeingDate: "2025-01-25",
      nextShoeingDate: "2025-03-01",
      shoeingType: "Herradura Barshoe (Herradura Cerrada de Barra)",
      farrierName: "Maestro Jairo Restrepo",
      cost: 260000,
      notes: "Soporte biomecánico para descompresión del tendón flexor.",
    },
    createdAt: "2025-02-01T08:30:00Z",
    updatedAt: "2025-02-19T10:00:00Z",
  },
  {
    id: "horse-5",
    name: "Princesa Gitana",
    breed: "Paso Fino Colombiano",
    gender: "hembra",
    coatColor: "Zaina",
    birthDate: "2022-09-01",
    ageYears: 3,
    microchip: "COL-982-003-889",
    passportNumber: "PFC-2022-870",
    ownerId: "cli-2",
    ownerName: "María Camila Gómez",
    pesebreraId: "box-05",
    pesebreraCode: "BOX-B02",
    healthStatus: "optimo",
    dietNotes: "Potranca en inicio de adiestramiento. Alimentación balanceada desarrollo.",
    imageUrl: "https://images.unsplash.com/photo-1566251037378-5e04e3bec343?auto=format&fit=crop&w=800&q=80",
    planCode: "TIPO_B",
    planName: "Pesebrera Tipo B (Forraje & Cama)",
    planPriceCOP: 1050000,
    dailyPortionsCount: 4,
    scheduledForRidingToday: true,
    assignedRiderName: "Montador Carlos Valderrama",
    ridingActivityType: "Cuerda y colocación de montura inicial",
    dailyActivityHistory: [
      {
        id: "act-h5-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-5",
        horseName: "Princesa Gitana",
        ownerId: "cli-2",
        ownerName: "María Camila Gómez",
        boxCode: "BOX-B02",
        portionsServedCount: 2,
        totalPortionsPlanned: 4,
        portionsDetails: [
          { portionNumber: 1, label: "Ración 1", served: true, servedAt: "06:30 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 2, label: "Ración 2", served: true, servedAt: "11:00 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 3, label: "Ración 3", served: false },
          { portionNumber: 4, label: "Ración 4", served: false },
        ],
        wasRidden: true,
        ridingScheduled: true,
        ridingActivity: "Trabajo inicial a la cuerda y aceptación de freno",
        riderName: "Montador Carlos Valderrama",
        generalCare: {
          bathed: true,
          hoovesCleaned: true,
          stableCleaned: true,
        },
        notes: "Excelente disposición, atenta a las instrucciones de voz.",
        completedAt: new Date(_nowMs - 1 * 3600000).toISOString(),
        reportedBy: "Mayordomo Cuadras",
        publishedToOwner: true,
      },
    ],
    pedigree: {
      sire: "Tormento de La Virginia F.C.",
      dam: "Gitana de Las Mercedes",
      grandSirePaternal: "Patrimonio del 8",
      grandDamPaternal: "Tormenta del Desierto",
      grandSireMaternal: "Bribón de San Isidro",
      grandDamMaternal: "Estrella del Camino",
      breedingFarm: "Criadero La Ilusión",
      registryNumber: "FED-PFC-94812",
      registrationDate: "2022-11-15",
    },
    diseaseHistory: [],
    farrierControl: {
      lastShoeingDate: "2025-02-10",
      nextShoeingDate: "2025-03-18",
      shoeingType: "Recorte Natural / Primer Herraje Liviano",
      farrierName: "Maestro Jairo Restrepo",
      cost: 120000,
      notes: "Adaptación excelente sin sensibilidad en la suela.",
    },
    createdAt: "2025-02-05T11:00:00Z",
    updatedAt: "2025-02-14T17:00:00Z",
  },
  {
    id: "horse-6",
    name: "Centinela de Oro",
    breed: "Criollo Colombiano",
    gender: "castrado",
    coatColor: "Bayo Cebruno",
    birthDate: "2017-11-03",
    ageYears: 9,
    microchip: "COL-982-004-123",
    passportNumber: "CCC-2017-542",
    ownerId: "cli-4",
    ownerName: "Valentina Osorio Ríos",
    pesebreraId: "box-06",
    pesebreraCode: "BOX-B03",
    healthStatus: "observacion",
    dietNotes: "Monitoreo por leve cólico resuelto. Dieta blanda con papilla de afrecho.",
    imageUrl: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80",
    planCode: "TIPO_A",
    planName: "Pesebrera Tipo A (Integral)",
    planPriceCOP: 1600000,
    dailyPortionsCount: 3,
    scheduledForRidingToday: true,
    assignedRiderName: "Herrador y Montador Auxiliar",
    ridingActivityType: "Pista suave de recuperación y paso",
    dailyActivityHistory: [
      {
        id: "act-h6-today",
        date: _fmtDate(_nowMs),
        horseId: "horse-6",
        horseName: "Centinela de Oro",
        ownerId: "cli-4",
        ownerName: "Valentina Osorio Ríos",
        boxCode: "BOX-B03",
        portionsServedCount: 1,
        totalPortionsPlanned: 3,
        portionsDetails: [
          { portionNumber: 1, label: "Ración 1", served: true, servedAt: "07:30 AM", servedBy: "Palafrenero Jorge" },
          { portionNumber: 2, label: "Ración 2", served: false },
          { portionNumber: 3, label: "Ración 3", served: false },
        ],
        wasRidden: true,
        ridingScheduled: true,
        ridingActivity: "Torno y trote corto en pista de arena",
        riderName: "Herrador y Montador Auxiliar",
        generalCare: {
          bathed: true,
          hoovesCleaned: true,
          stableCleaned: true,
        },
        notes: "Excelente recuperación, come papilla con buen ánimo.",
        completedAt: new Date(_nowMs - 2 * 3600000).toISOString(),
        reportedBy: "Mayordomo Cuadras",
        publishedToOwner: true,
      },
    ],
    pedigree: {
      sire: "Cacique Calarcá",
      dam: "Amapola Serrana",
      breedingFarm: "Hacienda El Porvenir",
      registryNumber: "CCC-10948",
    },
    diseaseHistory: [
      {
        id: "dis-5",
        diseaseName: "Laceración en Cuartilla Miembro Anterior Izquierdo",
        diagnosedDate: "2024-12-02",
        resolutionDate: "2024-12-16",
        severity: "leve",
        status: "resuelto",
        medicationsGiven: "Lavados antisépticos con Clorhexidina + Pomada cicatrizante Furacín",
        veterinarian: "Dr. Juan Pablo Morales (MVZ)",
        clinicalNotes: "Cicatrización completa por segunda intención sin formación de queloide.",
      },
    ],
    farrierControl: {
      lastShoeingDate: "2025-01-10",
      nextShoeingDate: "2025-02-15", // Ya vencido
      shoeingType: "Herradura Campestre de Trabajo Todo Terreno",
      farrierName: "Herrador Carlos Patiño",
      cost: 140000,
      notes: "Urgente programar cambio de herraduras por desgaste en lumbres.",
    },
    createdAt: "2025-02-10T09:30:00Z",
    updatedAt: "2025-02-20T08:15:00Z",
  },
  {
    id: "horse-7",
    name: "Zafiro de la Colina",
    breed: "Árabe",
    gender: "macho",
    coatColor: "Tordillo Blanco",
    birthDate: "2020-01-18",
    ageYears: 6,
    microchip: "COL-982-005-771",
    passportNumber: "ARB-2020-019",
    ownerId: "cli-2",
    ownerName: "María Camila Gómez",
    pesebreraId: null,
    pesebreraCode: null,
    healthStatus: "optimo",
    dietNotes: "Ingreso reciente a las instalaciones. Cuarentena previa superada.",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
    pedigree: {
      sire: "Al Hadiyah AA",
      dam: "Shahira Bint Malik",
      grandSirePaternal: "Laheeb Al Nasser",
      grandDamPaternal: "The Vision HG",
      grandSireMaternal: "Imperial Imdal",
      grandDamMaternal: "Bint Bint Shahira",
      breedingFarm: "Haras de la Colina",
      registryNumber: "AHR-672911",
      registrationDate: "2020-03-10",
    },
    diseaseHistory: [],
    farrierControl: {
      lastShoeingDate: "2025-02-14",
      nextShoeingDate: "2025-03-20",
      shoeingType: "Herradura de Aluminio para Deporte",
      farrierName: "Maestro Jairo Restrepo",
      cost: 200000,
      notes: "Cascos limpios y aplomos correctos.",
    },
    createdAt: "2025-02-18T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
];

export const initialPesebreras: Pesebrera[] = [
  {
    id: "box-01",
    code: "BOX-A01",
    name: "Pesebrera A-01",
    zone: "Nave Principal",
    type: "premium",
    status: "ocupada",
    monthlyPrice: 1200000,
    dimensions: "4.0m x 4.0m",
    horseId: "horse-1",
    horseName: "Relámpago de San Isidro",
    notes: "Bebedero automático revisado y cama de viruta fresca.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-10T10:30:00Z",
  },
  {
    id: "box-02",
    code: "BOX-A02",
    name: "Pesebrera A-02",
    zone: "Nave Principal",
    type: "estandar",
    status: "ocupada",
    monthlyPrice: 950000,
    dimensions: "3.5m x 3.5m",
    horseId: "horse-2",
    horseName: "Tormenta de La Alborada",
    notes: "Ventana con reja hacia el pasillo este.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-15T12:30:00Z",
  },
  {
    id: "box-03",
    code: "BOX-A03",
    name: "Pesebrera A-03",
    zone: "Nave Principal",
    type: "estandar",
    status: "ocupada",
    monthlyPrice: 950000,
    dimensions: "3.5m x 3.5m",
    horseId: "horse-3",
    horseName: "Monarca Real",
    notes: "Comedero de acero inoxidable y forrajera alta.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-20T09:00:00Z",
  },
  {
    id: "box-04",
    code: "BOX-B01",
    name: "Pesebrera B-01",
    zone: "Pabellón Norte",
    type: "premium",
    status: "ocupada",
    monthlyPrice: 1300000,
    dimensions: "4.5m x 4.0m",
    horseId: "horse-4",
    horseName: "Sultán del Valle",
    notes: "Piso de caucho vulcanizado antideslizante para confort articular.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-01T08:30:00Z",
  },
  {
    id: "box-05",
    code: "BOX-B02",
    name: "Pesebrera B-02",
    zone: "Pabellón Norte",
    type: "estandar",
    status: "ocupada",
    monthlyPrice: 950000,
    dimensions: "3.5m x 3.5m",
    horseId: "horse-5",
    horseName: "Princesa Gitana",
    notes: "Excelente ventilación natural transversal.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-05T11:00:00Z",
  },
  {
    id: "box-06",
    code: "BOX-B03",
    name: "Pesebrera B-03",
    zone: "Pabellón Norte",
    type: "estandar",
    status: "ocupada",
    monthlyPrice: 950000,
    dimensions: "3.5m x 3.5m",
    horseId: "horse-6",
    horseName: "Centinela de Oro",
    notes: "Ubicada frente al picadero techado.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-10T09:30:00Z",
  },
  {
    id: "box-07",
    code: "BOX-C01",
    name: "Pesebrera C-01",
    zone: "Ala Poniente",
    type: "estandar",
    status: "disponible",
    monthlyPrice: 950000,
    dimensions: "3.5m x 3.5m",
    horseId: null,
    horseName: null,
    notes: "Desinfectada y lista para recibir nuevo huésped.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T09:00:00Z",
  },
  {
    id: "box-08",
    code: "BOX-C02",
    name: "Pesebrera C-02",
    zone: "Ala Poniente",
    type: "paridera",
    status: "disponible",
    monthlyPrice: 1400000,
    dimensions: "5.0m x 5.0m",
    horseId: null,
    horseName: null,
    notes: "Cámara de vigilancia instalada para monitoreo nocturno.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-16T11:00:00Z",
  },
  {
    id: "box-09",
    code: "BOX-C03",
    name: "Pesebrera C-03",
    zone: "Ala Poniente",
    type: "paddock",
    status: "mantenimiento",
    monthlyPrice: 1100000,
    dimensions: "3.5m x 3.5m + corral",
    horseId: null,
    horseName: null,
    notes: "Reparación del cerramiento de madera y bisagras del portón exterior.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-19T16:00:00Z",
  },
  {
    id: "box-10",
    code: "BOX-C04",
    name: "Pesebrera C-04",
    zone: "Ala Poniente",
    type: "paddock",
    status: "disponible",
    monthlyPrice: 1100000,
    dimensions: "3.5m x 3.5m + corral",
    horseId: null,
    horseName: null,
    notes: "Con salida directa a corral de esparcimiento empastado.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
];

export const initialVeterinaryRecords: VeterinaryRecord[] = [
  {
    id: "vet-1",
    horseId: "horse-2",
    horseName: "Tormenta de La Alborada",
    type: "medicamento",
    title: "Infiltración Articular (Ácido Hialurónico + Glucosamina)",
    diagnosis: "Artropatía Degenerativa / Sinovitis de Corvejón",
    symptoms: "Rigidez inicial al salir de pesebrera, leve calor y distensión articular.",
    dosage: "1 dosis intraarticular de 4ml (20mg/ml)",
    route: "intraarticular",
    frequency: "Cada 15 días (Ciclo de 3 aplicaciones)",
    durationDays: 30,
    severity: "moderada",
    stableCareInstructions: "Vendar extremidad posterior, caminata de la mano 15 min al día, no pista fuerte.",
    administeredBy: "Dr. Juan Pablo Morales (MVZ)",
    date: "2025-02-18",
    nextDueDate: "2025-03-05",
    status: "en_curso",
    cost: 350000,
    chargeToOwner: true,
    notes: "Evolución positiva, disminución notable de la rigidez en corvejón.",
    createdAt: "2025-02-18T11:00:00Z",
    updatedAt: "2025-02-18T11:00:00Z",
  },
  {
    id: "vet-2",
    horseId: "horse-4",
    horseName: "Sultán del Valle",
    type: "control",
    title: "Ecografía Tendinosa y Terapia Regenerativa",
    diagnosis: "Desmitis en Tendón Flexor Digital Superficial (Mano Derecha)",
    symptoms: "Aumento de volumen en tercio medio metacarpiano con dolor moderado a la presión.",
    dosage: "Gel antiinflamatorio tópico + vendaje compresivo",
    route: "topica",
    frequency: "2 veces al día por 14 días",
    durationDays: 14,
    severity: "grave",
    stableCareInstructions: "Reposo absoluto en box, hidroterapia con agua fría 20 min mañana y tarde.",
    administeredBy: "Dra. Carolina Zuluaga (MVZ)",
    date: "2025-02-17",
    nextDueDate: "2025-02-27",
    status: "en_curso",
    cost: 220000,
    chargeToOwner: true,
    notes: "Microdesgarro en tendón flexor digital superficial en proceso de cicatrización con plasma.",
    createdAt: "2025-02-17T14:30:00Z",
    updatedAt: "2025-02-17T14:30:00Z",
  },
  {
    id: "vet-3",
    horseId: "horse-1",
    horseName: "Relámpago de San Isidro",
    type: "vacuna",
    title: "Vacunación Anual Encefalitis Equina y Tétanos",
    diagnosis: "Inmunización Preventiva y Certificación Oficial ICA",
    symptoms: "Constantes vitales normales (T: 37.8°C, FC: 36 lpm), apto para biológico.",
    dosage: "Refuerzo bivalente 2ml IM profunda en tabla del cuello",
    route: "intramuscular",
    frequency: "Dosis anual única",
    durationDays: 1,
    severity: "leve",
    stableCareInstructions: "Observación de temperatura por 24 horas, descanso de pista por 48 horas.",
    administeredBy: "Dr. Juan Pablo Morales (MVZ)",
    date: "2025-02-05",
    nextDueDate: "2026-02-05",
    status: "completado",
    cost: 140000,
    chargeToOwner: false,
    notes: "Certificado emitido para el pasaporte federado e historial oficial.",
    createdAt: "2025-02-05T09:00:00Z",
    updatedAt: "2025-02-05T09:00:00Z",
  },
  {
    id: "vet-4",
    horseId: "horse-6",
    horseName: "Centinela de Oro",
    type: "desparasitacion",
    title: "Desparasitación Interna con Ivermectina + Prazicuantel",
    diagnosis: "Control Antiparasitario Cuatrimestral Preventivo",
    symptoms: "Condición corporal 6/9, coprológico previo con conteo bajo de estrongilos.",
    dosage: "Jeringa pasta oral calibrada para 500 kg en comisura labial",
    route: "oral",
    frequency: "Dosis única periódica",
    durationDays: 1,
    severity: "leve",
    stableCareInstructions: "Suministrar en ayunas matutina antes del heno.",
    administeredBy: "Mayordomo Carlos Patiño",
    date: "2025-02-12",
    nextDueDate: "2025-05-12",
    status: "completado",
    cost: 65000,
    chargeToOwner: false,
    notes: "Tolerancia adecuada sin efectos secundarios ni cólico posterior.",
    createdAt: "2025-02-12T08:00:00Z",
    updatedAt: "2025-02-12T08:00:00Z",
  },
];

export const initialPayments: PaymentRecord[] = [
  {
    id: "pay-1",
    receiptNumber: "REC-2025-081",
    clientId: "cli-1",
    clientName: "Carlos Eduardo Restrepo",
    clientPhone: "+573124589012",
    horseId: "horse-1",
    horseName: "Relámpago de San Isidro",
    pesebreraCode: "BOX-A01",
    category: "integral",
    concept: "Mensualidad Pesebrera BOX-A01 + Servicios Febrero",
    amount: 1360000,
    items: [
      { concept: "Canon mensual Pesebrera Premium BOX-A01", amount: 1200000 },
      { concept: "Servicio de herraje especializado de pista", amount: 160000 },
    ],
    dueDate: "2025-02-05",
    paymentDate: "2025-02-03",
    status: "pagado",
    paymentMethod: "transferencia",
    bankDetails: "Bancolombia Ahorros # 108-928374-12 a nombre de Hacienda & Pesebreras SAS",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-03T16:20:00Z",
  },
  {
    id: "pay-2",
    receiptNumber: "REC-2025-082",
    clientId: "cli-1",
    clientName: "Carlos Eduardo Restrepo",
    clientPhone: "+573124589012",
    horseId: "horse-3",
    horseName: "Monarca Real",
    pesebreraCode: "BOX-A03",
    category: "alquiler_pesebrera",
    concept: "Mensualidad Pesebrera BOX-A03 - Febrero 2025",
    amount: 950000,
    items: [
      { concept: "Canon mensual Pesebrera Estándar BOX-A03", amount: 950000 },
    ],
    dueDate: "2025-02-05",
    paymentDate: "2025-02-03",
    status: "pagado",
    paymentMethod: "transferencia",
    bankDetails: "Bancolombia Ahorros # 108-928374-12 a nombre de Hacienda & Pesebreras SAS",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-03T16:20:00Z",
  },
  {
    id: "pay-3",
    receiptNumber: "REC-2025-083",
    clientId: "cli-2",
    clientName: "María Camila Gómez",
    clientPhone: "+573208901234",
    horseId: "horse-2",
    horseName: "Tormenta de La Alborada",
    pesebreraCode: "BOX-A02",
    category: "integral",
    concept: "Mensualidad BOX-A02 + Herraje Ortopédico - Febrero",
    amount: 1160000,
    items: [
      { concept: "Canon mensual Pesebrera Estándar BOX-A02", amount: 950000 },
      { concept: "Herraje ortopédico con cuña trasera", amount: 210000 },
    ],
    dueDate: "2025-02-10",
    status: "vencido",
    bankDetails: "Bancolombia Ahorros # 108-928374-12 a nombre de Hacienda & Pesebreras SAS (NIT: 901.482.110-3)",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "pay-4",
    receiptNumber: "REC-2025-084",
    clientId: "cli-2",
    clientName: "María Camila Gómez",
    clientPhone: "+573208901234",
    horseId: "horse-2",
    horseName: "Tormenta de La Alborada",
    pesebreraCode: "BOX-A02",
    category: "veterinaria",
    concept: "Tratamiento Articular y Medicamentos Especiales",
    amount: 350000,
    items: [
      { concept: "Dosis Intraarticular Ácido Hialurónico + Infiltración", amount: 350000 },
    ],
    dueDate: "2025-02-25",
    status: "pendiente",
    bankDetails: "Bancolombia Ahorros # 108-928374-12 a nombre de Hacienda & Pesebreras SAS",
    createdAt: "2025-02-18T12:00:00Z",
    updatedAt: "2025-02-18T12:00:00Z",
  },
  {
    id: "pay-5",
    receiptNumber: "REC-2025-085",
    clientId: "cli-3",
    clientName: "Andrés Felipe Mendoza",
    clientPhone: "+573016783456",
    horseId: "horse-4",
    horseName: "Sultán del Valle",
    pesebreraCode: "BOX-B01",
    category: "alquiler_pesebrera",
    concept: "Mensualidad Pesebrera Premium BOX-B01 - Febrero 2025",
    amount: 1300000,
    items: [
      { concept: "Canon mensual Pesebrera Premium BOX-B01 (Pabellón Norte)", amount: 1300000 },
    ],
    dueDate: "2025-02-05",
    paymentDate: "2025-02-04",
    status: "pagado",
    paymentMethod: "transferencia",
    bankDetails: "Bancolombia Ahorros # 108-928374-12 a nombre de Hacienda & Pesebreras SAS",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-04T10:10:00Z",
  },
];

export const initialInventory: InventoryItem[] = [
  {
    id: "inv-1",
    name: "Concentrado Pinta Campeón Equinos",
    category: "alimento",
    currentStock: 18,
    unit: "Bultos (40kg)",
    minStockAlert: 10,
    costPerUnit: 115000,
    location: "Bodega de Granos N° 1",
    supplier: "Italcol Colombia",
    lastRestocked: "2025-02-15",
    notes: "Alimento base para ejemplares adultos en mantenimiento y trabajo liviano.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "inv-2",
    name: "Concentrado Cinta Azul Potros & Reproducción",
    category: "alimento",
    currentStock: 4, // Stock crítico
    unit: "Bultos (40kg)",
    minStockAlert: 6,
    costPerUnit: 135000,
    location: "Bodega de Granos N° 1",
    supplier: "Finca / Alimentos Balanceados",
    lastRestocked: "2025-02-01",
    notes: "¡Alerta! Restan 4 bultos. Prioritario para potros y yeguas lactantes.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-18T00:00:00Z",
  },
  {
    id: "inv-3",
    name: "Heno de Alfalfa Deshidratada Premium",
    category: "heno",
    currentStock: 42,
    unit: "Pacas (25kg)",
    minStockAlert: 20,
    costPerUnit: 38000,
    location: "Heno Techado Sector Norte",
    supplier: "Agroalfalfa del Valle",
    lastRestocked: "2025-02-12",
    notes: "Proteína alta (18%), libre de moho y polvo.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-12T00:00:00Z",
  },
  {
    id: "inv-4",
    name: "Heno Pangola / Pasto de Corte",
    category: "heno",
    currentStock: 26,
    unit: "Pacas (20kg)",
    minStockAlert: 15,
    costPerUnit: 22000,
    location: "Heno Techado Sector Norte",
    supplier: "Finca El Porvenir",
    lastRestocked: "2025-02-17",
    notes: "Fibra digestiva para suplementación permanente en pesebre.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-17T00:00:00Z",
  },
  {
    id: "inv-5",
    name: "Viruta de Pino Blanca Aromatizada (Camas)",
    category: "cama",
    currentStock: 7, // Stock crítico
    unit: "Bultos Prensados",
    minStockAlert: 12,
    costPerUnit: 18000,
    location: "Bodega de Aserrín Externa",
    supplier: "Maderera Los Pinos",
    lastRestocked: "2025-02-05",
    notes: "Camas secas y desinfectadas. Solicitar pedido esta semana.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-18T00:00:00Z",
  },
  {
    id: "inv-6",
    name: "Flunixin Meglumine 100ml (Banamine)",
    category: "medicamento",
    currentStock: 5,
    unit: "Frascos (100ml)",
    minStockAlert: 2,
    costPerUnit: 92000,
    location: "Botiquín Veterinario Bajo Llave",
    supplier: "Distribuidora Veterinaria Equina",
    lastRestocked: "2025-02-10",
    notes: "Antiinflamatorio y analgésico visceral para cólicos y dolores músculo-esqueléticos.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-10T00:00:00Z",
  },
  {
    id: "inv-7",
    name: "Fenilbutazona Pasta Oral 33g",
    category: "medicamento",
    currentStock: 2, // Stock crítico
    unit: "Jeringas Orales",
    minStockAlert: 4,
    costPerUnit: 48000,
    location: "Botiquín Veterinario Bajo Llave",
    supplier: "Laboratorios Virbac",
    lastRestocked: "2025-01-20",
    notes: "Tratamiento de afecciones articulares en pesebre.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "inv-8",
    name: "Suplemento Articular Glucosamina + Condroitina",
    category: "suplemento",
    currentStock: 6,
    unit: "Potes (1kg)",
    minStockAlert: 2,
    costPerUnit: 140000,
    location: "Farmacia y Suplementos",
    supplier: "Equine Nutrition",
    lastRestocked: "2025-02-14",
    notes: "Para ejemplares de paso y trocha en entrenamiento intensivo.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-14T00:00:00Z",
  },
  {
    id: "inv-9",
    name: "Ivermectina + Prazicuantel Pasta Equina",
    category: "medicamento",
    currentStock: 14,
    unit: "Tubos Dosificadores",
    minStockAlert: 6,
    costPerUnit: 35000,
    location: "Botiquín Veterinario Bajo Llave",
    supplier: "Zoetis",
    lastRestocked: "2025-02-01",
    notes: "Desparasitante amplio espectro para ciclo trimestral.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-01T00:00:00Z",
  },
];

export const initialFeedTemplates: FeedTemplate[] = [
  {
    id: "tpl-1",
    name: "Concentrado Pinta Campeón (40kg)",
    brand: "Italcol",
    category: "alimento",
    defaultUnit: "Bultos (40kg)",
    defaultMinStockAlert: 8,
    defaultCostPerUnit: 125000,
    defaultLocation: "Bodega Principal de Alimentos",
    defaultSupplier: "Distribuidora Italcol Central",
    nutritionalNotes: "14% Proteína balanceada para caballos de paso y trocha en entrenamiento moderado.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-2",
    name: "Concentrado Cinta Azul Especial (40kg)",
    brand: "Italcol",
    category: "alimento",
    defaultUnit: "Bultos (40kg)",
    defaultMinStockAlert: 6,
    defaultCostPerUnit: 138000,
    defaultLocation: "Bodega Principal de Alimentos",
    defaultSupplier: "Distribuidora Italcol Central",
    nutritionalNotes: "Alta energía digestiva con avena rolada y aceites esenciales para ejemplares de pista.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-3",
    name: "Brío Potros & Lactancia (40kg)",
    brand: "Contegral",
    category: "alimento",
    defaultUnit: "Bultos (40kg)",
    defaultMinStockAlert: 5,
    defaultCostPerUnit: 145000,
    defaultLocation: "Bodega Principal de Alimentos",
    defaultSupplier: "Agropecuaria del Oriente",
    nutritionalNotes: "16% Proteína con aminoácidos ramificados para yeguas gestantes y potros en destete.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-4",
    name: "Pavo Nature's Best Muesli Fibra (20kg)",
    brand: "Pavo Equine",
    category: "alimento",
    defaultUnit: "Bolsas (20kg)",
    defaultMinStockAlert: 4,
    defaultCostPerUnit: 195000,
    defaultLocation: "Bodega Especial Climatizada",
    defaultSupplier: "Importadora Equina Gourmet",
    nutritionalNotes: "Muesli bajo en azúcar y almidón para caballos sensibles a cólicos o laminitis.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-5",
    name: "Heno Pangola Verde Extra (Paca)",
    brand: "Agroforrajes",
    category: "heno",
    defaultUnit: "Pacas",
    defaultMinStockAlert: 20,
    defaultCostPerUnit: 28000,
    defaultLocation: "Heno Techado - Bloque Norte",
    defaultSupplier: "Agroforrajes del Valle",
    nutritionalNotes: "Corte tierno, bajo polvo, fibra larga estimulante del tránsito digestivo cecal.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-6",
    name: "Alfalfa Deshidratada Premium (Paca 25kg)",
    brand: "Criadero Alfalfa",
    category: "heno",
    defaultUnit: "Pacas (25kg)",
    defaultMinStockAlert: 10,
    defaultCostPerUnit: 45000,
    defaultLocation: "Heno Techado - Bloque Norte",
    defaultSupplier: "Criadero & Forrajes Andinos",
    nutritionalNotes: "Alto contenido de calcio y proteína vegetal de primer nivel para condición corporal.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-7",
    name: "Viruta de Pino Blanca Tamizada y Seca",
    brand: "Maderas El Roble",
    category: "cama",
    defaultUnit: "Bolsones (50L)",
    defaultMinStockAlert: 15,
    defaultCostPerUnit: 18000,
    defaultLocation: "Bodega de Viruta y Camas",
    defaultSupplier: "Aserrío & Maderas El Roble",
    nutritionalNotes: "Absorbente aromática, secada en horno para prevenir alergias respiratorias.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-8",
    name: "Banamine (Flunixin Meglumina 100ml)",
    brand: "MSD Animal Health",
    category: "medicamento",
    defaultUnit: "Frascos (100ml)",
    defaultMinStockAlert: 3,
    defaultCostPerUnit: 165000,
    defaultLocation: "Botiquín Veterinario Bajo Llave",
    defaultSupplier: "Distribuidora Veterinaria Nacional",
    nutritionalNotes: "Antinflamatorio no esteroideo y analgésico visceral de emergencia para cólico.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-9",
    name: "Fenilbutazona Pasta Oral 20g",
    brand: "Zoetis",
    category: "medicamento",
    defaultUnit: "Jeringas Orales",
    defaultMinStockAlert: 4,
    defaultCostPerUnit: 48000,
    defaultLocation: "Botiquín Veterinario Bajo Llave",
    defaultSupplier: "Zoetis Colombia",
    nutritionalNotes: "Tratamiento de inflamaciones músculo-esqueléticas y cojeras agudas.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-10",
    name: "Suplemento Glucosamina + MSM + Condroitina",
    brand: "NutriEquine",
    category: "suplemento",
    defaultUnit: "Potes (1kg)",
    defaultMinStockAlert: 3,
    defaultCostPerUnit: 140000,
    defaultLocation: "Farmacia y Suplementos",
    defaultSupplier: "Equine Nutrition Lab",
    nutritionalNotes: "Condroprotector para articulaciones, corvejones y tendones de ejemplares de pista.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
];

export const initialCenterSettings: CenterSettings = {
  stableName: "Hacienda & Pesebreras San Isidro",
  location: "Vereda Las Palmas, Km 8 - Antioquia, Colombia",
  nit: "901.482.910-3",
  veterinarianName: "Dr. Juan Pablo Morales (MVZ)",
  veterinarianLicense: "COMVEZCOL # 19.842",
  veterinarianSpecialty: "Medicina y Reproducción Equina",
  bankDetails:
    "Bancolombia Cuenta de Ahorros # 108-928374-12 a nombre de Hacienda & Pesebreras SAS",
  tagline: "Centro Integral de Reproducción, Alojamiento y Cuidado Equino",
  contactPhone: "+57 312 458 9012",
};

export const initialCanonPlans: CanonPlan[] = [
  {
    id: "plan-tipo-a",
    code: "TIPO_A",
    name: "Pesebrera Tipo A",
    tagline: "El criadero se encarga de todo (Servicio Integral)",
    description:
      "Modalidad completa donde el criadero asume la alimentación balanceada, herrajes de pista, montador profesional, agua fresca permanente, cama desinfectada y administración de vitaminas/suplementos.",
    basePriceCOP: 1600000,
    basePlazaCOP: 300000,
    isActive: true,
    inclusions: [
      { id: "inc-1", name: "Comida / Concentrado", included: true, costCOP: 350000, notes: "3 raciones diarias de concentrado según peso y plan nutricional" },
      { id: "inc-2", name: "Herraje Especializado", included: true, costCOP: 180000, notes: "Herraduras de pista y nivelación de cascos cada 35 días" },
      { id: "inc-3", name: "Montador / Adiestrador", included: true, costCOP: 250000, notes: "Entrenamiento diario en picadero, pista y acondicionamiento físico" },
      { id: "inc-4", name: "Agua Permanente", included: true, costCOP: 50000, notes: "Bebedero automático con agua limpia y fresca 24/7" },
      { id: "inc-5", name: "Cama / Viruta Limpia", included: true, costCOP: 120000, notes: "Recambio de viruta tratada con cal y limpieza profunda 2 veces al día" },
      { id: "inc-6", name: "Vitaminas & Suplementos", included: true, costCOP: 80000, notes: "Suministro diario de electrolitos, biotina y complementos veterinarios" },
      { id: "inc-7", name: "Heno / Forraje Verde", included: true, costCOP: 170000, notes: "Pasto de corte fresco y heno de gramínea de alta palatabilidad" },
      { id: "inc-8", name: "Paseador & Baño Semanal", included: true, costCOP: 100000, notes: "Sesiones en caminador, solarium y baño regular de acondicionamiento" },
    ],
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "plan-tipo-b",
    code: "TIPO_B",
    name: "Pesebrera Tipo B",
    tagline: "El criadero se encarga de Agua, Heno y Cama",
    description:
      "Modalidad intermedia donde el criadero garantiza el agua fresca permanente, suministro diario de heno de pasto y mantenimiento de cama limpia. El concentrado, vitaminas, herraje y monta son coordinados por el propietario.",
    basePriceCOP: 1050000,
    basePlazaCOP: 680000,
    isActive: true,
    inclusions: [
      { id: "inc-1", name: "Agua Permanente", included: true, costCOP: 50000, notes: "Bebedero automático y agua fresca constante 24/7" },
      { id: "inc-2", name: "Heno / Forraje", included: true, costCOP: 200000, notes: "Suministro diario de heno seleccionado en henera" },
      { id: "inc-3", name: "Cama / Viruta Limpia", included: true, costCOP: 120000, notes: "Limpieza y viruta de pino fresca suministrada por el criadero" },
      { id: "inc-4", name: "Comida / Concentrado", included: false, costCOP: 350000, notes: "A cargo del propietario (se custodia en la bodega del criadero)" },
      { id: "inc-5", name: "Herraje Especializado", included: false, costCOP: 180000, notes: "A cargo del propietario o facturado como servicio adicional" },
      { id: "inc-6", name: "Montador / Adiestrador", included: false, costCOP: 250000, notes: "A cargo del propietario" },
      { id: "inc-7", name: "Vitaminas & Suplementos", included: false, costCOP: 80000, notes: "A cargo del propietario" },
    ],
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "plan-tipo-c",
    code: "TIPO_C",
    name: "Pesebrera Tipo C",
    tagline: "El criadero se encarga de Agua y Cama (Básico)",
    description:
      "Alojamiento esencial donde el criadero brinda la plaza con agua limpia permanente y mantenimiento de cama. Toda la alimentación (heno y concentrado) y los cuidados de herraje y ejercicio corren por cuenta del propietario.",
    basePriceCOP: 750000,
    basePlazaCOP: 580000,
    isActive: true,
    inclusions: [
      { id: "inc-1", name: "Agua Permanente", included: true, costCOP: 50000, notes: "Bebedero automático y agua fresca 24/7" },
      { id: "inc-2", name: "Cama / Viruta Limpia", included: true, costCOP: 120000, notes: "Mantenimiento diario de cama de viruta y aseo del box" },
      { id: "inc-3", name: "Heno / Forraje", included: false, costCOP: 200000, notes: "A cargo del propietario (debe traer pacas al establo)" },
      { id: "inc-4", name: "Comida / Concentrado", included: false, costCOP: 350000, notes: "A cargo del propietario" },
      { id: "inc-5", name: "Herraje Especializado", included: false, costCOP: 180000, notes: "A cargo del propietario" },
      { id: "inc-6", name: "Montador / Adiestrador", included: false, costCOP: 250000, notes: "A cargo del propietario" },
      { id: "inc-7", name: "Vitaminas & Suplementos", included: false, costCOP: 80000, notes: "A cargo del propietario" },
    ],
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
];

export function calculateMetrics(
  pesebreras: Pesebrera[],
  horses: Horse[],
  clients: Client[],
  payments: PaymentRecord[],
  inventory?: InventoryItem[]
): DashboardMetrics {
  const totalBoxes = pesebreras.length;
  const occupiedBoxes = pesebreras.filter((b) => b.status === "ocupada").length;
  const availableBoxes = pesebreras.filter((b) => b.status === "disponible").length;
  const occupancyRate = totalBoxes > 0 ? Math.round((occupiedBoxes / totalBoxes) * 100) : 0;

  const totalHorses = horses.length;
  const horsesInTreatment = horses.filter(
    (h) => h.healthStatus === "en_tratamiento" || h.healthStatus === "reposo"
  ).length;

  const today = new Date().toISOString().split("T")[0];
  const horsesWithOverdueFarrier = horses.filter(
    (h) => h.farrierControl && h.farrierControl.nextShoeingDate < today
  ).length;

  const activeClients = clients.length;

  const monthlyRevenue = payments
    .filter((p) => p.status === "pagado")
    .reduce((acc, curr) => acc + curr.amount, 0);

  const pendingPayments = payments.filter((p) => p.status !== "pagado");
  const pendingPaymentsCount = pendingPayments.length;
  const pendingPaymentsTotal = pendingPayments.reduce((acc, curr) => acc + curr.amount, 0);

  const lowStockItemsCount = (inventory || initialInventory).filter(
    (item) => item.currentStock <= item.minStockAlert
  ).length;

  return {
    totalBoxes,
    occupiedBoxes,
    availableBoxes,
    occupancyRate,
    totalHorses,
    horsesInTreatment,
    horsesWithOverdueFarrier,
    lowStockItemsCount,
    activeClients,
    monthlyRevenue,
    pendingPaymentsCount,
    pendingPaymentsTotal,
  };
}

export const initialUsers: UserAccount[] = [
  {
    id: "usr-admin",
    username: "admin",
    name: "Administrador General",
    role: "admin",
    password: "admin",
    email: "admin@centropesebreras.com",
    phone: "+573001234567",
    active: true,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "usr-vet",
    username: "veterinario",
    name: "Dr. Juan Pablo Morales (MVZ)",
    role: "veterinario",
    password: "vet",
    email: "vet.morales@sanidadequina.com",
    phone: "+573119876543",
    active: true,
    createdAt: "2025-01-05T09:00:00Z",
  },
  {
    id: "usr-mayordomo",
    username: "mayordomo",
    name: "Carlos Restrepo (Jefe de Cuadras)",
    role: "mayordomo",
    password: "cuadras",
    email: "carlos.mayordomo@pesebreras.com",
    phone: "+573123456789",
    active: true,
    createdAt: "2025-01-08T10:00:00Z",
  },
  {
    id: "usr-propietario",
    username: "propietario",
    name: "María Camila Gómez",
    role: "propietario",
    password: "prop",
    email: "camilagomez@criaderolailusion.co",
    phone: "+573208901234",
    linkedClientId: "cli-2",
    active: true,
    createdAt: "2025-01-15T12:00:00Z",
  },
  {
    id: "usr-montador",
    username: "montador",
    name: "Mateo Jaramillo (Montador)",
    role: "montador",
    password: "monta",
    email: "mateo.pista@hacienda.com",
    phone: "+573155554321",
    active: true,
    createdAt: "2025-01-20T08:00:00Z",
  },
  {
    id: "usr-palafrenero",
    username: "palafrenero",
    name: "Hernán Ospina (Palafrenero)",
    role: "palafrenero",
    password: "cuadra",
    email: "hernan.cuadras@hacienda.com",
    phone: "+573167778899",
    active: true,
    createdAt: "2025-01-22T07:00:00Z",
  },
];
