import { UserRole, RoleDefinition } from "@/types";

export const USER_ROLES: Record<UserRole, RoleDefinition> = {
  admin: {
    id: "admin",
    title: "Administrador General",
    subtitle: "Control Total, Canones y Parámetros",
    badge: "Super Admin",
    emoji: "👑",
    color: "bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30",
    allowedTabs: [
      "resumen",
      "pesebreras",
      "caballos",
      "propietarios",
      "sanidad",
      "finanzas",
      "inventario",
      "ajustes",
      "operativo_montador",
      "portal_propietario",
    ],
    defaultTab: "resumen",
  },
  mayordomo: {
    id: "mayordomo",
    title: "Mayordomo / Cuadras",
    subtitle: "Pesebreras, Asignaciones e Insumos",
    badge: "Jefe de Cuadras",
    emoji: "🤠",
    color: "bg-emerald-500/15 text-emerald-800 dark:text-emerald-300 border-emerald-500/30",
    allowedTabs: ["resumen", "pesebreras", "caballos", "inventario", "operativo_montador"],
    defaultTab: "pesebreras",
  },
  veterinario: {
    id: "veterinario",
    title: "Médico Veterinario",
    subtitle: "Historial Clínico, Fármacos y Sanidad",
    badge: "Salud Equina",
    emoji: "🩺",
    color: "bg-rose-500/15 text-rose-800 dark:text-rose-300 border-rose-500/30",
    allowedTabs: ["sanidad", "caballos"],
    defaultTab: "sanidad",
  },
  montador: {
    id: "montador",
    title: "Montador Directo",
    subtitle: "Pista, Torno y Actividades Asignadas",
    badge: "Pista & Monta",
    emoji: "🏇",
    color: "bg-amber-500/15 text-amber-800 dark:text-amber-300 border-amber-500/30",
    allowedTabs: ["operativo_montador", "caballos"],
    defaultTab: "operativo_montador",
  },
  palafrenero: {
    id: "palafrenero",
    title: "Palafrenero / Cuadras",
    subtitle: "Raciones de Comida y Aseo de Box",
    badge: "Cuadra & Aseo",
    emoji: "🌾",
    color: "bg-sky-500/15 text-sky-800 dark:text-sky-300 border-sky-500/30",
    allowedTabs: ["operativo_montador", "pesebreras"],
    defaultTab: "operativo_montador",
  },
  propietario: {
    id: "propietario",
    title: "Portal del Propietario",
    subtitle: "Mis Equinos, Canones y Recibos",
    badge: "Cliente Externo",
    emoji: "📱",
    color: "bg-purple-500/15 text-purple-800 dark:text-purple-300 border-purple-500/30",
    allowedTabs: ["portal_propietario"],
    defaultTab: "portal_propietario",
  },
};

export const ROLE_LIST: RoleDefinition[] = Object.values(USER_ROLES);
